all: apache-solr-3.5.0.tgz mongodb-osx-x86_64-2.0.1.tgz

apache-solr-3.5.0.tgz:
	wget -O apache-solr-3.5.0.tgz http://www.trieuvan.com/apache/lucene/solr/3.5.0/apache-solr-3.5.0.tgz

mongodb-osx-x86_64-2.0.1.tgz:
	wget -O mongodb-osx-x86_64-2.0.1.tgz http://fastdl.mongodb.org/osx/mongodb-osx-x86_64-2.0.1.tgz

